## workflow build config

# id and name for the workflow (bundle id = domain.id)
id: alfred-image-optim-workflow

# base domain
domain: com.tumblr.ramiroaraujo

name: Optimize Images
description: Image optimization workflow based on ImageOptim-CLI (https://github.com/JamieMason/ImageOptim-CLI) from Jamie Mason.
created_by: Ramiro Araujo
website: https://github.com/ramiroaraujo/alfred-image-optim-workflow
readme: readme

## development config

# path is the relative path to the workflow in the project root
path: workflow

# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Dropbox